apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: promptcorp
  labels:
    app: promptcorp-mongodb
    tier: database
    environment: production
spec:
  clusterIP: None
  selector:
    app: promptcorp-mongodb
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP
